auth:
  handler: auth/function.handler
  # cors:
  #   origin: ${self:custom.corsOrigin}

connect:
  events:
    - websocket:
        route: $connect
        authorizer:
          name: ${self:service}-auth #TODO: fix loadFunctions.js to handle this...
  handler: connect/function.handler

disconnect:
  events:
    - websocket:
        route: $disconnect
  handler: disconnect/function.handler

StartSendMessageNotification:
  handler: startSendMessageNotification/function.handler
  events:
    - sns:
        arn: arn:aws:sns:us-west-1:101010101010:TransactionsProcessedTopic

GetConnection:
  handler: getConnection/function.handler

SendMessage:
  handler: sendMessage/function.handler
  
# default:
#   events:
#     - websocket:
#         route: $default
#   handler: default/function.handler

# broadcast:
#   events:
#     - websocket:
#         route: broadcast
#   handler: broadcast/function.handler
