connect:
  events:
    - websocket:
        route: $connect
        authorizer:
            name: auth
            identitySource:
              - route.request.header.Auth
  handler: connect/function.handler

disconnect:
  events:
    - websocket:
        route: $disconnect
  handler: disconnect/function.handler

default:
  events:
    - websocket:
        route: $default
  handler: default/function.handler

broadcast:
  events:
    - websocket:
        route: broadcast
  handler: broadcast/function.handler

auth:
  handler: auth/function.handler
  # cors:
  #   origin: ${self:custom.corsOrigin}
