ConnectionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-connections
    AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
    KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
