AccountBalanceNotification:
  handler: Accounts.Functions::Platform8.Accounts.Functions.AccountBalanceNotification::Handler
  runtime: dotnetcore3.1
  package:
    artifact: services/Accounts/accounts-deploy-package.zip

StartProcessAccountBalanceNotification:
  handler: startProcessAccountBalanceNotification/function.handler
  events:
    - sns:
        arn: arn:aws:sns:us-west-1:101010101010:AccountBalanceTopic
