${self:service}-ProcessAccountBalanceNotification:
  definition:
    Comment: Process AccountBalanceTopic
    StartAt: AccountBalanceNotification
    States:
      AccountBalanceNotification:
        Type: Task
        Resource:
          Fn::GetAtt: [AccountBalanceNotification, Arn]
        End: true
