// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platform8.BudgetService.Data;

namespace BudgetService.Api.Migrations
{
    [DbContext(typeof(BudgetDataContext))]
    [Migration("20210724020037_Budget-and-Categories")]
    partial class BudgetandCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Platform8.BudgetService.Data.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Platform8.BudgetService.Data.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Platform8.BudgetService.Data.Category", b =>
                {
                    b.HasOne("Platform8.BudgetService.Data.Budget", "Budget")
                        .WithMany("Categories")
                        .HasForeignKey("BudgetId");

                    b.OwnsOne("Platform8.Core.NumberRange", "Allocation", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("End")
                                .HasPrecision(10, 4)
                                .HasColumnType("decimal(10,4)");

                            b1.Property<decimal>("Start")
                                .HasPrecision(10, 4)
                                .HasColumnType("decimal(10,4)");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("Allocation");

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Platform8.BudgetService.Data.Budget", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
