${self:service}-ProcessUploadedTransactions:
  definition:
    Comment: Process Transactions step function
    StartAt: GetFileProcessor
    States:
      GetFileProcessor:
        Type: Task
        Resource:
          Fn::GetAtt: [GetFileProcessor, Arn]
        Next: ProcessTransactions
      ProcessTransactions:
        Type: Task
        Resource:
          Fn::GetAtt: [ProcessTransactions, Arn]
        Next: PublishTransactionProcessingResults
      PublishTransactionProcessingResults:
        Type: Task
        Resource:
          Fn::GetAtt [PublishTransactionProcessingResults, Arn]
        End: true

${self:service}-ProcessExpenseAddedNotification:
  definition:
    Comment: Add expense as a LinkedItem to Transaction step function
    StartAt: ProcessMessage
    States:
      ProcessMessage:
        Type: Task
        Resource:
          Fn::GetAtt: [ProcessMessage, Arn]
        Next: AddLinkedItem
      AddLinkedItem:
        Type: Task
        Resource:
          Fn::GetAtt: [AddLinkedItem, Arn]
        Next: PublishAddLinkedItemResults
      PublishAddLinkedItemResults:
        Type: Task
        Resource:
          Fn::GetAtt [PublishAddLinkedItemResults, Arn]
        End: true
