name: Publish main Storybooks

on:
  push:
    branches: [main]

jobs:
  storybooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: npm install and lerna bootstrap
        run: |
          npm install -g npm@latest
          npm install silent
          npm run bootstrap
      - name: Build Storybooks
        run: npm run deploy-storybook:local
      - name: Commit Storybooks to gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
        run: |
          cp -r $GITHUB_WORKSPACE/main/storybooks/* $GITHUB_WORKSPACE/gh-pages
        run: |
          git add .
          git commit -m "Deploying to GitHub Pages 🚀"
          git push
      # - name: Push to gh-pages
      #   uses: Automattic/action-commit-to-branch@master
      #   with:
      #     branch: gh-pages
      #     commit_message: Deploying to GitHub Pages 🚀
      #     env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
      # - name: Deploy to GitHub Pages 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.5
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: Pages # The folder the action should deploy.
