name: Publish PR Storybooks

on:
  pull_request:
    branches: [main]

jobs:
  storybooks:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v2
        with:
          path: branch
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: npm install and lerna bootstrap
        run: |
          npm install -g npm@latest
          npm install silent
          npm run bootstrap
      - name: Build Storybooks
        run: npm run deploy-storybook:local
      - name: Copy static Storybooks to Pages
        run: |
          mkdir -p Pages/${{ github.head_ref }}
          cp -r storybooks/* Pages/${{ github.head_ref }}
      - name: Commit Storybooks to gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
        run: |
          cp -R $GITHUB_WORKSPACE/branch/Pages/* $GITHUB_WORKSPACE/gh-pages
        run: |
          git add .
          git commit -m "Deploying to GitHub Pages 🚀"
          git push
      # - name: Copy static Storybooks to Pages
      #   run: |
      #     mkdir -p Pages/${{ github.head_ref }}
      #     cp -r storybooks/* Pages/${{ github.head_ref }}
      # - name: Deploy to GitHub Pages 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.5
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: Pages # The folder the action should deploy.
      - name: Add comment to PR with link to Storybooks
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Review the Storybooks for this PR at https://kfinley.github.io/Platform8/${{github.head_ref}}'
            })
