name: Publish main Storybooks

on:
  push:
    branches: [main]
    paths:
      - packages/vue2-*/src/stories/**
      - packages/vue2-*/src/components/**

jobs:
  storybooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: npm install and lerna bootstrap
        run: |
          cd $GITHUB_WORKSPACE/main
          npm install -g npm@latest
          npm install silent
          npm run bootstrap
      - name: Build Storybooks
        run: |
          cd $GITHUB_WORKSPACE/main
          npm run deploy-storybook:local
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Commit Storybooks to gh-pages branch #gh-pages branch must exist
        run: |
          cd $GITHUB_WORKSPACE/gh-pages
          cp -r $GITHUB_WORKSPACE/main/storybooks/* $GITHUB_WORKSPACE/gh-pages
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .

          if git diff-index --quiet HEAD --; then
              echo 'No changes to commit';
          else
              git commit -m "Deploying to GitHub Pages 🚀";
              git push;
          fi

