apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../../dev-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: platform8-ses
  name: platform8-ses
spec:
  ports:
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    io.kompose.service: platform8-ses
status:
  loadBalancer: {}
