apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../../dev-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: platform8-dynamodb-admin
  name: platform8-dynamodb-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: platform8-dynamodb-admin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ../../dev-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: platform8-dynamodb-admin
    spec:
      containers:
      - env:
        - name: DYNAMO_ENDPOINT
          value: http://platform8.dynamodb:8000
        image: aaronshaf/dynamodb-admin
        imagePullPolicy: ""
        name: platform8.dynamodb.admin
        ports:
        - containerPort: 8001
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
