apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../../dev-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: platform8-sls
  name: platform8-sls
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  - name: "3002"
    port: 3002
    targetPort: 3002
  - name: "4002"
    port: 4002
    targetPort: 4002
  - name: "4569"
    port: 4569
    targetPort: 4569
  selector:
    io.kompose.service: platform8-sls
status:
  loadBalancer: {}
