apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../../dev-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: platform8-budgets
  name: platform8-budgets
spec:
  ports:
  - name: "5003"
    port: 5003
    targetPort: 5003
  selector:
    io.kompose.service: platform8-budgets
status:
  loadBalancer: {}
