apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../../dev-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: platform8-storybooks
  name: platform8-storybooks
spec:
  ports:
  - name: "6006"
    port: 6006
    targetPort: 6006
  selector:
    io.kompose.service: platform8-storybooks
status:
  loadBalancer: {}
