apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../../dev-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: platform8-expenses
  name: platform8-expenses
spec:
  ports:
  - name: "5004"
    port: 5004
    targetPort: 5004
  selector:
    io.kompose.service: platform8-expenses
status:
  loadBalancer: {}
